#ifndef _EMWINDEMO_H
#define _EMWINDEMO_H

#include "main.h"

#define CONTROL_D1_HIGH     HAL_GPIO_WritePin(CONTROL_D1_GPIO_Port,CONTROL_D1_Pin,GPIO_PIN_SET)
#define CONTROL_D1_LOW      HAL_GPIO_WritePin(CONTROL_D1_GPIO_Port,CONTROL_D1_Pin,GPIO_PIN_RESET)
#define CONTROL_D2_HIGH     HAL_GPIO_WritePin(CONTROL_D2_GPIO_Port,CONTROL_D2_Pin,GPIO_PIN_SET)
#define CONTROL_D2_LOW      HAL_GPIO_WritePin(CONTROL_D2_GPIO_Port,CONTROL_D2_Pin,GPIO_PIN_RESET)
#define CONTROL_D3_HIGH     HAL_GPIO_WritePin(CONTROL_D3_GPIO_Port,CONTROL_D3_Pin,GPIO_PIN_SET)
#define CONTROL_D3_LOW      HAL_GPIO_WritePin(CONTROL_D3_GPIO_Port,CONTROL_D3_Pin,GPIO_PIN_RESET)
#define CONTROL_D4_HIGH     HAL_GPIO_WritePin(CONTROL_D4_GPIO_Port,CONTROL_D4_Pin,GPIO_PIN_SET)
#define CONTROL_D4_LOW      HAL_GPIO_WritePin(CONTROL_D4_GPIO_Port,CONTROL_D4_Pin,GPIO_PIN_RESET)
#define CONTROL_D5_HIGH     HAL_GPIO_WritePin(CONTROL_D5_GPIO_Port,CONTROL_D5_Pin,GPIO_PIN_SET)
#define CONTROL_D5_LOW      HAL_GPIO_WritePin(CONTROL_D5_GPIO_Port,CONTROL_D5_Pin,GPIO_PIN_RESET)
#define CONTROL_D6_HIGH     HAL_GPIO_WritePin(CONTROL_D6_GPIO_Port,CONTROL_D6_Pin,GPIO_PIN_SET)
#define CONTROL_D6_LOW      HAL_GPIO_WritePin(CONTROL_D6_GPIO_Port,CONTROL_D6_Pin,GPIO_PIN_RESET)

//用户自定义消息
#define WM_SHOW_MSG (WM_USER+1)
#define WM_AUTO_MSG (WM_USER+2)

void emwinDemo(void);

#endif
