//
// Created by Y on 2020/10/10.
//

#ifndef ZJA003_PROJECT_PARALLELCOMMUNICATION_H
#define ZJA003_PROJECT_PARALLELCOMMUNICATION_H

#include "main.h"

#define FPGA_DATA0		    HAL_GPIO_ReadPin(FPGA_DATA0_GPIO_Port,FPGA_DATA0_Pin)
#define FPGA_DATA1		    HAL_GPIO_ReadPin(FPGA_DATA1_GPIO_Port,FPGA_DATA1_Pin)
#define FPGA_DATA2		    HAL_GPIO_ReadPin(FPGA_DATA2_GPIO_Port,FPGA_DATA2_Pin)
#define FPGA_DATA3		    HAL_GPIO_ReadPin(FPGA_DATA3_GPIO_Port,FPGA_DATA3_Pin)
#define FPGA_DATA4		    HAL_GPIO_ReadPin(FPGA_DATA4_GPIO_Port,FPGA_DATA4_Pin)
#define FPGA_DATA5		    HAL_GPIO_ReadPin(FPGA_DATA5_GPIO_Port,FPGA_DATA5_Pin)
#define FPGA_DATA6		    HAL_GPIO_ReadPin(FPGA_DATA6_GPIO_Port,FPGA_DATA6_Pin)
#define FPGA_DATA7		    HAL_GPIO_ReadPin(FPGA_DATA7_GPIO_Port,FPGA_DATA7_Pin)
#define FPGA_DATA8		    HAL_GPIO_ReadPin(FPGA_DATA8_GPIO_Port,FPGA_DATA8_Pin)
#define FPGA_DATA9		    HAL_GPIO_ReadPin(FPGA_DATA9_GPIO_Port,FPGA_DATA9_Pin)
#define FPGA_DATA10		    HAL_GPIO_ReadPin(FPGA_DATA10_GPIO_Port,FPGA_DATA10_Pin)
#define FPGA_DATA11		    HAL_GPIO_ReadPin(FPGA_DATA11_GPIO_Port,FPGA_DATA11_Pin)
#define FPGA_DATA12		    HAL_GPIO_ReadPin(FPGA_DATA12_GPIO_Port,FPGA_DATA12_Pin)
#define FPGA_DATA13		    HAL_GPIO_ReadPin(FPGA_DATA13_GPIO_Port,FPGA_DATA13_Pin)
#define FPGA_DATA14		    HAL_GPIO_ReadPin(FPGA_DATA14_GPIO_Port,FPGA_DATA14_Pin)
#define FPGA_DATA15		    HAL_GPIO_ReadPin(FPGA_DATA15_GPIO_Port,FPGA_DATA15_Pin)
#define FPGA_DATA_CS_HIGH	HAL_GPIO_WritePin(FPGA_DATA_CS_GPIO_Port, FPGA_DATA_CS_Pin,GPIO_PIN_SET)
#define FPGA_DATA_CS_LOW		HAL_GPIO_WritePin(FPGA_DATA_CS_GPIO_Port, FPGA_DATA_CS_Pin,GPIO_PIN_RESET)

void getWaveData(void);

#endif //ZJA003_PROJECT_PARALLELCOMMUNICATION_H
